### ISSUE TITLE
商品一覧

### ISSUE THREAD

**Issue by Takatatsu9** [danielkaneko/Shopping-Cart#1]
- `list`コマンドで商品一覧を表示する
- 商品はそれぞれ「商品名」「商品説明」「価格」「在庫」のパラメーターを持っている
- 10品ぐらい欲しい
  - 厳密にピッタリ10品でなくてもいい。多くてもいいが、少ないのは困る
  - 100〜300円ぐらいの価格帯が3割、4桁帯が4割、残りは5桁超えぐらいのラインナップがいいかな
- `--オプション`で検索条件の指定
  - `--name 名前`で、曖昧一致検索
  - `--price 価格-価格`で、その価格内に収まる商品を検索
  - `--sort オプション`で検索結果の昇順ソート
    - `--sort name`で商品名ソート
    - `--sort price`で価格順ソート

**Comment by danielkaneko** [comment]
商品の表示について質問をさせていただきたいのですが、

1. `list`コマンドでの商品の表示は商品を登録した昇順ですか？または降順ですか？
2. `--sort name`での商品名ソートは名前の昇順でしょうか？または降順でしょうか？
3. `--soft price`での価格ソートは価格の昇順でしょうか？または降順でしょうか？
4. コマンドの入力は大文字を認めますか？

**Comment by Takatatsu9** [comment]
1. 特に決まりはありません
2. 既に書いてある通りです
3. 既に書いてある通りです
4. gitのコマンドがどうかで小文字のみか混ざってもOKか決めてください

**Comment by danielkaneko** [comment]
ありがとうございます。

**Comment by danielkaneko** [comment]
商品の表示方法について質問させていただきたいのですが、
商品を表示する際、「商品名」「商品説明」「価格」「在庫」の全てを表示しますか？
全てを表示する必要がない場合はどれを表示すればよいでしょうか？

**Comment by Takatatsu9** [comment]
全て表示でお願いします

**Comment by danielkaneko** [comment]
ありがとうございます。
承知いたしました。

**Comment by danielkaneko** [comment]
機能について質問させていただきたいのですが、

1. コマンドの入力受付の形式に何かご希望はございますか。
2. コマンドが正しくなかった場合のメッセージ表記は必要でしょうか。また、必要である場合はどのようなメッセージを表示すればよいでしょうか。
3. 検索条件を指定した際、その条件に当てはまる商品が存在しなかった場合のメッセージ表記は必要でしょうか。また、必要である場合はどのようなメッセージを表示すればよいでしょうか。
4. 商品を表示後、もう一度コマンド入力を受け付ける機能は必要でしょうか。

**Comment by Takatatsu9** [comment]
1. どういう意味ですか？
2. そんなコマンドは無い、"-help"や"-?"でヒントが表示できるみたいなメッセージをお願いします
3. 条件に一致する商品が見つからない旨のメッセージをお願いします
4. どういう意味ですか？

**Comment by danielkaneko** [comment]
>1. どういう意味ですか？

コマンドを入力する際に(コマンドを入力してください：)等のメッセージを表示する必要はありますか。もしも必要なのであれば、どのようなメッセージを表示すればよいでしょうか。

> 4.どういう意味ですか？

現在、コマンドを入力し商品を表示後、機能が終了してしまいます。
終了させずに何度でもコマンドを入力できるようにいたしますか。

**Comment by Takatatsu9** [comment]
1. 不要です
4. どちらでも構いません
（終了させる方法だとやれるもんならやってみろって難易度ですよ？）

**Comment by danielkaneko** [comment]
ありがとうございます。
> 2.どちらでも構いません

につきましては、何度でもコマンドを入力できるような形で作業を進めさせていただきます。

**Comment by Takatatsu9** [comment]
コマンドが正しくなかった場合のメッセージの回答に書いたヘルプ機能なんですが、
別でissue立てました #4 。このissueの対応でヘルプ表示対応を混ぜる必要はありません。

**Comment by danielkaneko** [comment]
承知いたしました。

**Comment by danielkaneko** [comment]
機能について質問させていただきたいのですが、

1. 「この金額だけで検索したい」シチュエーションとして`--price 200-200`ではなく`--price 200`という入力を有効にいたしますか？

2. 並べ替え機能にて`--asc`や`--desc`の入力追加で昇順、降順を切り替えを可能にいたしますか？
もしも切り替え機能を追加する際には入力を`--sort name --desc`のようにいたしますか？

3. 並べ替え機能にて複数項目での並び替えを可能にいたしますか？
もしも複数項目での並び替えを可能にするのであれば、入力が`--sort name price`の場合、名前の並び替えの後、同名商品の並び替えを行うという形でよろしいでしょうか？

**Comment by Takatatsu9** [comment]
1. 1円単位で完全一致した商品だけを探したいというシチュエーションがまず考えられないので、不要です
2. 欲しいです。ただし、`asc` `desc`のハイフンは不要です
3. それでお願いします

**Comment by danielkaneko** [comment]
承知いたしました。

**Comment by Takatatsu9** [comment]
仕様変更
- 商品ID（一意の値）をもたせる

**Comment by danielkaneko** [comment]
承知いたしました。
